export default function AboutPage() {
  return (
    <div className="space-y-6">
      <h1 className="text-3xl text-accent-primary tracking-tight">about</h1>
      <div className="grid md:grid-cols-[220px,1fr] gap-6 items-start">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src="/headshot.jpeg"
          alt="hannah wimpy"
          className="w-48 h-48 md:w-56 md:h-56 rounded-md object-cover border"
          style={{ filter: 'saturate(0.9) contrast(1.1) hue-rotate(-8deg)' }}
        />
        <div className="space-y-4 text-sm text-text-secondary">
          <p>I GREW UP IN FRANKLIN, TENNESSEE AND I AM NOW BASED IN BOSTON. I WAS THE KID TAKING APART TOYS TO SEE HOW THE GEARS MESSED WITH THE LIGHTS. A MICROSCOPE ARRIVED WHEN I WAS FIVE. BY TEN, I HAD A LAB POSITION AT LIPSCOMB UNIVERSITY. THE THEME NEVER CHANGED: BUILD A THING, WATCH IT TOUCH THE REAL WORLD, LEARN FROM THE FEEDBACK LOOP.</p>
          <p>I AM TWENTY-ONE. I FOUNDED, OPERATED, AND EXITED A DRUG DISCOVERY AUTOMATION STARTUP: A LAB-IN-THE-LOOP SYSTEM WITH REAL‑TIME INFERENCE AND AN END‑TO‑END BIOINFORMATICS PIPELINE. THAT EXPERIENCE LOCKED IN WHAT I CARE ABOUT — PHYSICAL AI — SYSTEMS WHERE SOFTWARE ACTUALLY INTERACTS WITH, CONTROLS, AND LEARNS FROM HARDWARE.</p>
          <p>AT NORTHEASTERN, I SELF‑DESIGNED A COMPUTATIONAL BIOPHYSICS MAJOR ACROSS COMPUTER SCIENCE, BIOCHEMISTRY, AND PHYSICS. I AM A STAMPS SCHOLAR WITH A BUNCH OF OTHER AWARDS, BUT MORE IMPORTANTLY I LIKE SHIPPING THINGS. MY RESEARCH TRACK RAN THROUGH HARVARD MEDICAL SCHOOL AND NORTHEASTERN ON VOLTAGE‑GATED ION CHANNELS, WHICH NATURALLY LED ME TO LAB AUTOMATION.</p>
          <p>TODAY I WORK ON NEXT‑GEN AI PRODUCT AT LILA SCIENCES — BUILDING THE ORCHESTRATION LAYER FOR SCIENTIFIC SUPERINTELLIGENCE: THE SYSTEMS GLUE BETWEEN HARDWARE, ROBOTICS, AND PLATFORM.</p>
          <p>I AM EXPLORING SUMMER AND FALL 2026 OPPORTUNITIES ACROSS PHYSICAL AI, EMBODIED SYSTEMS, LAB AUTOMATION, AND DEFENSE TECH. DMS OPEN.</p>
        </div>
      </div>
    </div>
  )
}
